### ISSUE TITLE
Add Page View Tracking

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/transportation-dockless-dataviz#93]
We need to quantify viewership/impact of this tool, ideally ahead of launch next week. Can we add Google Analytics?

**Comment by mateoclarke** [comment]
Do mean you just want to measure how many pageviews we get after the press release on Monday? Or did you have other ideas/goals in monitoring traffic?

GA has been in the code base since 2018-11-06. See commit https://github.com/cityofaustin/transportation-dockless-dataviz/commit/77a9f875febb80183c083fdf191f7c18ddfb591c

![screen shot 2019-01-11 at 1 55 43 pm](https://user-images.githubusercontent.com/5697474/51056782-63d3ec00-15a9-11e9-9cba-222647f0b86a.png)

I'm using coaatdamd@gmail.com account. Lmk if I should be using a different GA user.

**Comment by mateoclarke** [comment]
Closing after talking IRL
